#!/usr/bin/env yaml
# -*- coding: utf-8 -*-
# =============================================================================
# Created By  : Peem Srinikorn
# Created Date: Tue Sep  8 20:57:59 +07 2020
# =============================================================================
service_account: '372371376210-compute@developer.gserviceaccount.com'
steps:
# This step runs the unit tests on the app
- name: 'python:3.6-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r requirements.txt && pytest -v'

# This step builds the container image.

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '.'
  
# This step pushes the image to Container Registry

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'

# Deploy image to Cloud Run Google Cloud 
- name: 'gcr.io/cloud-builders/gcloud'
  id : Deploy to Cloud Run
  args:
  - 'run'
  - 'deploy'
  - 'fastapi-movies'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '--region'
  - asia-southeast1 
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
